---
title: "Tarea 3. Análisis Exportaciones totales y Google (GOOGL)"
author: "Adolfo Lopantzi Vazquez"
lang: es
format:
  html:
    grid:
      body-width: 1200px 
---



```{python}
#| echo: false

import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import pandas as pd

import matplotlib.ticker as ticker
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import calendar
import statsmodels.api as sm
import statsmodels.graphics.tsaplots as tsaplots
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.seasonal as seasonal
```


## Indicadores Económicos del INEGI


```{python}
#| code-fold: true

data_inegi = pd.read_excel("TIE_Inegi_long.xlsx")
data_inegi.info()
```



### Exportaciones totales

```{python}
#| code-fold: true
df_Exportacionestotales = data_inegi[["Fecha", "Exportaciones_totales"]].dropna()
df_Exportacionestotales.info()
print(f"Fecha de inicio: {df_Exportacionestotales['Fecha'].min()}")
print(f"Fecha de fin: {df_Exportacionestotales['Fecha'].max()}")
print("------")

print("Estadísticas descriptivas de Exportaciones totales:")
print(df_Exportacionestotales["Exportaciones_totales"].describe())
```



**Serie temporal de Exportaciones totales**

```{python}
#| code-fold: true

# Configurar la columna "Fecha" como índice para facilitar la manipulación de datos y la creación de gráficos de series temporales.
df_Exportacionestotales.set_index("Fecha", inplace=True)
# Definición de la serie temporal
exportaciones_ts = df_Exportacionestotales["Exportaciones_totales"]
print(exportaciones_ts.info())
```


**Gráfica de la serie temporal de Exportaciones totales**

```{python}
#| code-fold: true
#| fig-align: "center"

plt.figure(figsize=(12, 6))
plt.plot(exportaciones_ts.index, exportaciones_ts.values, marker='o', ms=3)
plt.title('Exportaciones Totales')
plt.xlabel('Fecha')
plt.ylabel('Número de Exportaciones totales')
plt.grid(alpha=0.3)
plt.show()
```

Filtramos datos a partir de 2016 para observar mejor la tendencia en los últimos años.

```{python}
#| code-fold: true
#| fig-align: "center"
exportaciones_ts_2016 = exportaciones_ts[exportaciones_ts.index >= "2016-01-01"]
plt.figure(figsize=(12, 6))
plt.plot(exportaciones_ts_2016.index, exportaciones_ts_2016.values, marker='o', ms=5)
plt.title('Exportaciones Totales (Desde 2016)')
plt.xlabel('Fecha')
plt.ylabel('Número de Exportaciones totales')
plt.grid(alpha=0.3)
plt.show()
```


**Gráfica interactiva de la serie temporal de Exportaciones totales**


```{python}
#| code-fold: true
#| fig-align: "center"


fig = px.line(x = exportaciones_ts_2016.index, y = exportaciones_ts_2016.values, title='Exportaciones Totales', labels={'y': 'Número de Exportaciones totales', 'x': 'Fecha'})
fig.update_xaxes(rangeslider_visible=True)
```


**Comparación anual Exportaciones totales**


```{python}
#| code-fold: true
#| fig-align: "center"

# Preparación de datos para la gráfica de comparación anual
df_exportacionestotales_anual = exportaciones_ts_2016.reset_index()
df_exportacionestotales_anual['Año'] = df_exportacionestotales_anual['Fecha'].dt.year
df_exportacionestotales_anual['Mes'] = df_exportacionestotales_anual['Fecha'].dt.month
df_exportacionestotales_anual["Nombre_mes"] = df_exportacionestotales_anual['Fecha'].dt.strftime('%b')


plt.figure(figsize=(12, 6))
sns.lineplot(data=df_exportacionestotales_anual, x='Nombre_mes', y='Exportaciones_totales', hue='Año', marker='o', palette='Set2')
plt.title('Comparación Anual de Exportaciones Totales')
plt.xlabel('Mes')
plt.ylabel('Número de Exportaciones Totales')
plt.legend(title='Año', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()
```

**Comparación mensual de Exportaciones Totales**

```{python}
#| code-fold: true
#| fig-align: "center"

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_exportacionestotales_anual, x='Año', y='Exportaciones_totales', hue='Nombre_mes', marker='o', palette='Set2')
plt.title('Comparación Mensual de Exportaciones Totales')
plt.xlabel('Año')
plt.ylabel('Número de Exportaciones Totales')
plt.legend(title='Mes', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()
```




```{python}
#| code-fold: true
#| fig-align: "center"

fig = px.line(df_exportacionestotales_anual, x='Año', y='Exportaciones_totales', markers=True, color='Nombre_mes', title='Comparación Mensual de Exportaciones Totales', labels={'Exportaciones_totales': 'Número de Exportaciones Totales'})
fig.update_layout(legend_title_text='Mes', plot_bgcolor='rgba(176, 196, 222, 0)', xaxis=dict(tickmode='linear'))
fig.update
fig.update_xaxes(dtick=1, gridcolor='rgba(120, 144, 156, 0.55)')
fig.update_yaxes(gridcolor='rgba(120, 144, 156, 0.55)')

```


**Boxplot trimestral de Exportaciones Totales**

```{python}
#| code-fold: true
#| fig-align: "center"

df_exportacionestotales_anual['Trimestre'] = df_exportacionestotales_anual['Fecha'].dt.to_period('Q')

# Variable combinada de año y trimestre para el eje x
df_exportacionestotales_anual['Año_Trimestre'] = df_exportacionestotales_anual['Año'].astype(str) + '-Q' + df_exportacionestotales_anual['Trimestre'].dt.quarter.astype(str)

plt.figure(figsize=(12, 6))
sns.boxplot(data=df_exportacionestotales_anual, x='Año_Trimestre', y='Exportaciones_totales', hue='Año', palette= 'Accent')
plt.title('Boxplot Trimestral de Exportaciones Totales')
plt.xlabel('Año-Trimestre')
plt.ylabel('Número de Exportaciones Totales')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.legend(title='Año', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()


```


**Heatmap de Exportaciones Totales**


```{python}
#| code-fold: true
#| fig-align: "center"

# Preparación de datos para el heatmap
heatmap_data = df_exportacionestotales_anual.pivot_table(index='Mes', columns='Año', values='Exportaciones_totales')

plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data, annot=True, linewidths=0.5, fmt=".1e", cmap='viridis')
plt.title('Heatmap de Exportaciones Totales por Mes y Año')
plt.xlabel('Año')
plt.ylabel('Mes')
plt.yticks(ticks = np.linspace(0.5, 11.5, 12), labels=[calendar.month_abbr[i] for i in range(1, 13)], rotation=0)
plt.show()
```


**Superficie exportaciones totales**

```{python}
#| code-fold: true
#| fig-align: "center"

Z = heatmap_data.values
X = heatmap_data.columns.astype(str) #Años
Y = calendar.month_abbr[1:13] #Meses

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, 
                contours=dict(
        x=dict(
            show=True,          # Líneas por año sobre la superficie
            color="whitesmoke",
            width=2
        ),
        y=dict(
            show=True,          # Líneas por mes sobre la superficie
            color="whitesmoke",
            width=2
        )
    ),
                colorscale='viridis')])
fig.update_layout(title='Superficie exportaciones totales',
                  scene=dict(xaxis_title='Año', yaxis_title='Mes', zaxis_title='Número de Exportaciones Totales'),
                  autosize=True,
                  height=600)
```



**Descomposición aditiva de la serie temporal de exportaciones totales**

```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición aditiva de la serie temporal de exportaciones totales"

decomposition_add = seasonal.seasonal_decompose(exportaciones_ts_2016, model='additive', period=12)

plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(exportaciones_ts_2016,color='#e8703a')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_add.trend,color='#0e7c7b')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_add.seasonal,color='#3d348b')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_add.resid,color='#b5179e')
plt.title('Ruido')
plt.tight_layout()
plt.show()

```


**Descomposición multiplicativa de la serie temporal de exportaciones totales**

```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición multiplicativa de la serie temporal de exportaciones totales"

decomposition_mul = seasonal.seasonal_decompose(exportaciones_ts_2016, model='multiplicative', period=12)
plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(exportaciones_ts_2016,color='#e8703a')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_mul.trend,color='#0e7c7b')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_mul.seasonal,color='#3d348b')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_mul.resid,color='#b5179e')
plt.title('Ruido')
plt.tight_layout()
plt.show()
```

## Valores financieros (enfoque en Google)

Ahora vamos a graficar las series temporales de los precios de las acciones de Google (GOOGL), Microsoft (MSFT), Nvidia (NVDA), Tesla (TSLA) y Meta (META) utilizando la biblioteca `yfinance` para obtener los datos históricos de las acciones y `matplotlib` para visualizarlos. Esto nos permitirá analizar la evolución de los precios de estas acciones a lo largo del tiempo y comparar su desempeño. El periodo de análisis se establece desde el 1 de enero de 2020 hasta el 31 de diciembre de 2025, lo que nos brinda una visión completa de su comportamiento durante estos años.


```{python}
#| code-fold: true
#| fig-align: "center"

tickers = ["GOOGL", "MSFT", "NVDA", "TSLA", "META"]
start_date = "2020-01-01"
end_date = "2025-12-31"

df_yf = yf.download(tickers, start=start_date, end=end_date, interval="1d")["Close"]
```

**Gráfica de los precios de las acciones**

```{python}
#| code-fold: true
#| fig-align: "center"

fig = go.Figure()
for ticker in tickers:
    fig.add_trace(go.Scatter(x=df_yf.index, y=df_yf[ticker], name=ticker))
fig.update_layout(title='Precios de las acciones (2020-2025)', xaxis_title='Fecha', yaxis_title='Precio (USD)', legend_title_text='Acciones', hovermode='x unified')
fig.update_xaxes(rangeslider_visible=True, gridcolor='rgba(120, 144, 156, 0.55)')
fig.update_yaxes(gridcolor='rgba(120, 144, 156, 0.55)')
fig.show()  
```


```{python}
print(type(df_yf))
print(df_yf.columns.tolist())
print(df_yf.head(2))
```


**Candlestick de GOOGL**

```{python}
#| code-fold: true
#| fig-align: "center"

df_GOOGL_ohlc = yf.download("GOOGL", start='2025-11-01', end='2025-12-31', interval="1d")
GOOGL = df_GOOGL_ohlc.xs("GOOGL", level=1, axis=1)

fig = go.Figure(data=[go.Candlestick(x=GOOGL.index,
                open=GOOGL['Open'],
                high=GOOGL['High'],
                low=GOOGL['Low'],
                close=GOOGL['Close'])])
fig.update_layout(title='Gráfico de Velas de GOOGL (2020-2025)', xaxis_title='Fecha', yaxis_title='Precio (USD)')
fig.update_xaxes(rangeslider_visible=True, gridcolor='rgba(120, 144, 156, 0.55)')
fig.update_yaxes(gridcolor='rgba(120, 144, 156, 0.55)')
fig.show()
```



**Resumen estadístico de los precios de GOOGL**

```{python}
#| code-fold: true

GOOGL_ts = df_yf["GOOGL"].dropna()
print(GOOGL_ts.info())
print(f"Fecha de inicio: {GOOGL_ts.index.min()}")
print(f"Fecha de fin: {GOOGL_ts.index.max()}")
print("------")
print("Estadísticas descriptivas de GOOGL:")
print(GOOGL_ts.describe())

```

**Comparación anual de GOOGL**


```{python}
#| code-fold: true
#| fig-align: "center"

GOOGL_df = GOOGL_ts.reset_index()
GOOGL_df['Año'] = GOOGL_df['Date'].dt.year
GOOGL_df['Mes'] = GOOGL_df['Date'].dt.month
GOOGL_df["Nombre_mes"] = GOOGL_df['Date'].dt.strftime('%b')
GOOGL_df['Dia_año']   = GOOGL_df['Date'].dt.dayofyear 

plt.figure(figsize=(12, 6))
sns.lineplot(data=GOOGL_df, x='Nombre_mes', y='GOOGL', hue='Año', marker='o', palette='Set2')
plt.title('Comparación Anual de GOOGL (Mensual)')
plt.xlabel('Mes')
plt.ylabel('Precio (USD)')
plt.legend(title='Año', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()
```




```{python}
#| code-fold: true
#| fig-align: "center"

#| code-fold: true
#| fig-align: "center"

plt.figure(figsize=(12, 6))
sns.lineplot(
    data=GOOGL_df,
    x='Dia_año',
    y='GOOGL',
    hue='Año',
    palette='Set2',
    errorbar=None
)

# Reemplazar números de día por nombres de mes en el eje X

meses_dias = [1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335]
meses_nombres = ['Ene','Feb','Mar','Abr','May','Jun',
                 'Jul','Ago','Sep','Oct','Nov','Dic']
plt.xticks(ticks=meses_dias, labels=meses_nombres)

plt.title('Comparación Anual de GOOGL (Diaria)')
plt.xlabel('Mes')
plt.ylabel('Precio (USD)')
plt.legend(title='Año', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()
```


**Boxplot trimestral de GOOGL**


```{python}
#| code-fold: true
#| fig-align: "center"


GOOGL_df['Trimestre'] = GOOGL_df['Date'].dt.to_period('Q')
GOOGL_df['Año_Trimestre'] = GOOGL_df['Año'].astype(str) + '-Q' + GOOGL_df['Trimestre'].dt.quarter.astype(str)

plt.figure(figsize=(12, 6))
sns.boxplot(data=GOOGL_df, x='Año_Trimestre', y='GOOGL', hue='Año', palette= 'Accent')
plt.title('Boxplot Trimestral de GOOGL')
plt.xlabel('Año-Trimestre')
plt.ylabel('Precio (USD)')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.legend(title='Año', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()
```

**Heatmap de GOOGL**


```{python}
#| code-fold: true
#| fig-align: "center"

# Crear columna de día del año para ordenar correctamente
GOOGL_df['Mes-dia']  = GOOGL_df['Date'].dt.strftime('%b-%d')


heatmap_data_googl = GOOGL_df.pivot_table(
    index='Mes-dia',
    columns='Año',
    values='GOOGL'
)

# Ordenar por día del año (no alfabéticamente)
orden = (GOOGL_df.drop_duplicates('Mes-dia')
                 .sort_values('Dia_año')['Mes-dia']
                 .tolist())
heatmap_data_googl = heatmap_data_googl.reindex(orden)

# Rellenar NaN para eliminar líneas blancas
heatmap_data_googl = heatmap_data_googl.ffill().bfill()

plt.figure(figsize=(12, 8))
sns.heatmap(
    heatmap_data_googl,
    annot=False,
    cmap='viridis',
    linewidths=0,        
    linecolor='none'     
)
plt.title('Heatmap de GOOGL por Fecha y Año')
plt.xlabel('Año')
plt.ylabel('Fecha')

plt.tight_layout()
plt.show()
```


**Superficie de GOOGL**


```{python}
#| code-fold: true
#| fig-align: "center"

Z = heatmap_data_googl.values
X = heatmap_data_googl.columns.astype(str) #Años
Y = heatmap_data_googl.index #Fechas

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, 
                contours=dict(
        x=dict(
            show=True,          # Líneas por año sobre la superficie
            color="whitesmoke",
            width=2
        ),
        y=dict(
            show=True,          # Líneas por fecha sobre la superficie
            color="whitesmoke",
            width=2
        )
    ),
                colorscale='viridis')])
fig.update_layout(title='Superficie de GOOGL', scene=dict(xaxis_title='Año', yaxis_title='Fecha', zaxis_title='Precio (USD)'), autosize=True, height=600)
```

**Descomposición aditiva de GOOGL**


```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición aditiva de la serie temporal de GOOGL"


# Utilizar periodo de 252 para capturar la estacionalidad anual en datos diarios (252 días hábiles por año que es el estándar en finanzas)
decomposition_add_googl = seasonal.seasonal_decompose(GOOGL_ts, model='additive', period=252)
plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(GOOGL_ts,color='#e8703a')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_add_googl.trend,color='#0e7c7b')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_add_googl.seasonal,color='#3d348b')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_add_googl.resid,color='#b5179e')
plt.title('Ruido')
plt.tight_layout()
plt.show()
```

**Descomposición multiplicativa de GOOGL**


```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición multiplicativa de la serie temporal de GOOGL"

decomposition_mul_googl = seasonal.seasonal_decompose(GOOGL_ts, model='multiplicative', period=252)
plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(GOOGL_ts,color='#e8703a')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_mul_googl.trend,color='#0e7c7b')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_mul_googl.seasonal,color='#3d348b')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_mul_googl.resid,color='#b5179e')
plt.title('Ruido')
plt.tight_layout()
plt.show()
```

# Conclusiones
Para las exportaciones totales se observa cómo crecen con los años, pero en 2020 ocurre la pandemia y es ahí donde el indicador cae de forma importante, para después recuperarse e incluso superar los niveles previos, impulsado por el fenómeno de relocalización (nearshoring) de los años recientes. 
Para Google (Alphabet) se observa también un crecimiento sostenido, con una caída importante en 2020, aunque se recupera con rapidez y continúa creciendo; esto se explica por la fortaleza de su negocio de publicidad digital y de servicios en la nube, que se beneficiaron del mayor uso de internet durante y después de la pandemia.
